### ISSUE TITLE
Generalize testing notebook

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#101]
Right now some of the paths are local to @rgerkin . Since we're going to try running this via TravisCI we will need to change those paths. There may also be other repos/libraries to install (in setup.py) for this to work.

**Comment by rgerkin** [comment]
@travs 
I think best practice would be to assume that `import channelworm` in the notebook will import a version that has the example IV curve data (and I think it does now after some recent merges).  In Travis we can make sure that this works by doing `pip install git+https://github.com/VahidGh/ChannelWorm@tests`, which will use the tests branch.

**Comment by travs** [comment]
@rgerkin 
Trying to run this locally but I'm getting an error. Do you know off hand what [this is saying](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb) (at bottom)?

**Comment by rgerkin** [comment]
@travs You need to upgrade sciunit.  I should have put a check for this in the notebook.

**Comment by rgerkin** [comment]
@travs The new field `last_model` allows the test to remember the last model that it was executed against, which allows one to add various convenience methods provided by the model to the `score` in `compute_score`.

**Comment by travs** [comment]
Closed by #115
