### ISSUE TITLE
Add Authentication to web app

### ISSUE THREAD

**Issue by miladjafary** [VahidGh/ChannelWorm#103]

**Comment by travs** [comment]
@miladjafary 
Hey! :smile: 
How is this issue progressing so far?

**Comment by miladjafary** [comment]
HI
auth module active now I should upload it to repo.
but i am working on the user dashboard for CRUD operation
I hope finish it on the weekend

**Comment by travs** [comment]
@miladjafary 
Ok this is exciting! I see this as the only roadblock right now to accomplishing some data entry with @stripathy and @vahidgh

If there is anything I can do to help move this along please let me know :-)
