### ISSUE TITLE
Unable to run tests in django project

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#107]
I'm trying to write some tests for the django project, but when I run `./manage.py test` I get an error :frowning: 

[output](http://hastebin.com/onujiqomud)

@miladjafary @VahidGh 
Do you guys have any idea what may be going on here?

**Comment by miladjafary** [comment]
@travs I think you should sync db .run this : 

./manage.py makemigrations ion_channel
./manage.py migrate

it could be help. let me know if it is not work.

**Comment by VahidGh** [comment]
@travs, Do a fresh clone and see if you get the same error (or remove all the files in the `migrations` directory under `ion_channel` directory).
The web app is working well after new changes in the OpenShift, so this should not happen with codes exactly as same as the master branch of the repo!

**Comment by travs** [comment]
This one is closed now. I had to delete all but `__init__.py` in `ion_channel/migrations`, then do 
```
./manage.py makemigrations ion_channel
./manage.py migrate
```
