### ISSUE TITLE
Augment models with metadata

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#13]
Add metadata to the PyOpenWorm channelworm API and NeuroML files: 
* For annotation, it is possible to add RDF based annotations to NeuroML files. [ex 1](https://github.com/NeuroML/NeuroML2/blob/master/examples/NML2_FullCell.nml), [ex 2](https://github.com/OpenSourceBrain/GranuleCell/blob/master/neuroConstruct/generatedNeuroML2/Gran_CaHVA_98.channel.nml), [ref](http://co.mbine.org/standards/qualifiers)
* Also we should add the modeler/contributors' name to the model/file

**Comment by travs** [comment]
Closed by openworm/PyOpenWorm#134
