### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#14]
For model validation, based on discussions from [here](https://gitter.im/openworm/muscle_model?at=54edde417928f3d27eabd0cc):
> "Validation framework is here: https://github.com/OpenSourceBrain/osb-model-validation. Best way to get a feel for this is to clone & install that and try one of the OSB models locally, e.g. https://github.com/OpenSourceBrain/MorrisLecarModel and run: omv all, to run all the tests. See the .test* files for the tests to perform, e.g. https://github.com/OpenSourceBrain/MorrisLecarModel/blob/master/NeuroML2/.test.jnml.w.omt and the MEP files for the Model emergent properties to compare against: https://github.com/OpenSourceBrain/MorrisLecarModel/blob/master/NeuroML2/.test.mep"

Also, it is possible to implement unit tests using [sciunit](https://github.com/scidash/sciunit) + [neuronunit](https://github.com/rgerkin/neuronunit)

**Comment by travs** [comment]
We've made some progress on this, so we can close it based on the new issues raised in the verification & validation milestone.
