### ISSUE TITLE
Build a pipeline for modeling ion channels with patch-clamp data available

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#16]
Develop a toolkit for digitization, fitting and optimization of HH models from patch-clamp experiments:
- [x] Look for a patch clamp study, extract data, and digitize needed figures as a case study (using [WebPlotDigitizer](http://arohatgi.info/WebPlotDigitizer/app/) + [Plotly](https://plot.ly))
- [ ] Fit parameters, and simulate the experiment using some GA and ODE algorithm (use/customize [Neurotune](https://github.com/pgleeson/neurotune)+[Pyelectro](https://github.com/pgleeson/pyelectro) where needed)
- [ ] Readjust parameters if needed and optimize the model to find the best fit
- [ ] Get plots + NeuroML2 outputs
- [ ] Validate the model (using [OSB model validation](https://github.com/OpenSourceBrain/osb-model-validation), and [Sciunit+Neuronunit](https://github.com/scidash/neuronunit), and Travis CI)
- [ ] Document the process

**Comment by VahidGh** [comment]
[This issue](https://github.com/openworm/muscle_model/issues/31) and [This study](https://github.com/openworm/OpenWorm/issues/31#issuecomment-69594374) could be a good starting point.

**Comment by VahidGh** [comment]
[this issue](https://github.com/openworm/muscle_model/issues/18) could be a good case study for the optimization process.

**Comment by miladjafary** [comment]
@VahidGh  I can't understand your mean about Pipeline. 
You mean the output of a module would be the input of another module?

**Comment by VahidGh** [comment]
My comment was regarding to tasks, should be done for implementing this module.
But from the designer (use case) point of view, the pipeline which end user would see is:
1. user uploads either plots (including V-t, I-t, I-V, G-V, and activation/inactivation kinetics) or raw data from patch-clamp experiment
1.2. If plots were uploaded, then he/she would digitize it via implemented digitizer, an get the raw data.
2. Then the raw data would be used in a fitting algorithm to simulate the experiment.
3. User will compare the result with the experiment, and if it was not ok, he/she would try a readjustment (the decision on the best fit could be made using something like Neurontune).
4. User will get final NeuroML2+plots as outputs
5. The final model would be validated and stored (and could be used in other modules such as the simulation module)

**Comment by joebowen** [comment]
Do we have an existing Django project that we want to add these features too?  Or are we looking at starting up a new one and how do we want to go about that?  

Also, how are we doing this manually in it's current state?  Do we have a list of example commands that are currently used to do this?

**Comment by VahidGh** [comment]
@joebowen, as discussed @miladjafary has started to work on the platform and design, and I'm working more on the scientific part of the modeling (both from patch-clamp studies and estimation).
Still there is no chosen framework, but I think Django would be interesting.
For now, we can start with the digitization process (see the first comment, and also #17), get numbers as a .csv file, and pass to the optimization module (some script based on the Neurotune).

**Comment by joebowen** [comment]
Django would be nice, it would allow us to easily integrate the existing scripts and commands into the web project side.  Where are we thinking of hosting the Django project?

@miladjafary, What do you have started for the platform and design?

**Comment by VahidGh** [comment]
I have no plan for the hosting. we can start locally (or some open hosting such as [openshift](https://www.openshift.com/web-hosting/python)) for now, and after the first release, we can discuss more with Stephen and ask for his help (maybe running this under the OpenWorm.org domain and other options for hosting!)

**Comment by joebowen** [comment]
Openshift looks like a good idea to start development in.  I can work on
setting up a django project on there.

**Comment by joebowen** [comment]
URL: http://channelwormdjango-channelworm.rhcloud.com/
Git Clone URL: ssh://550783004382ec36e60000dd@channelwormdjango-channelworm.rhcloud.com/~/git/channelwormdjango.git/

for the git clone, I have to add your ssh key to the settings to allow you access. Instructions are on the main url.  Just send me the ssh key and I'll add you.

**Comment by VahidGh** [comment]
@joebowen, great. So we can start some front end issues such as #17.

**Comment by slarson** [comment]
@joebowen Is there a repo you have for the channelworm cloud app? :)

**Comment by joebowen** [comment]
Yes, but it's on OpenShift.  I can get the information for it this evening.

**Comment by slarson** [comment]
@joebowen thanks!

**Comment by joebowen** [comment]
One issue is that to get access to the code, people have to send me their
OpenShift username and ssh public key, so I can add the permissions to the
account.  There might be a better way to manage that.

**Comment by slarson** [comment]
Perhaps to put the code on GitHub?

**Comment by joebowen** [comment]
I tried but then it doesn't update to the cloud server.  We could keep two
copies but then we risk divergent releases.

**Comment by joebowen** [comment]
If someone can figure out a better release process, it would probably help
quite a bit.

**Comment by travs** [comment]
Maybe we can use git hooks to sync the github and cloud versions?

**Comment by joebowen** [comment]
Possible.  The storage on the cloud server is git based.

**Comment by miladjafary** [comment]
Hi.

I think we can develop code in the git and use GitHub as a source code controller and use open shift as deployment environment. 
Every time that a new version of code exist we can deploy it on the open shift.

**Comment by slarson** [comment]
Hi all; doing some clean up on the issues in here; I think this issue encompasses the entire effort we are putting in across all the other issues and milestones.  Therefore, we're breaking up this effort into smaller cards and smaller milestones that have definite end points.  Closing this for now.  See the re-defined and relabelled milestones in this project for where this has gone.
