### ISSUE TITLE
Digitize plots from patch-clamp studies

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#17]
The scenario is that a user, would need to upload a plot from a patch-clamp study, and extract digitized data for further analysis. (See [this issue](https://github.com/openworm/muscle_model/issues/20#issuecomment-72691023), and [this one](https://github.com/openworm/muscle_model/issues/30#issuecomment-72689142) for more information)

The digitization process could be implemented via the [WebPlotDigitizer](http://arohatgi.info/WebPlotDigitizer/app/) and it's open source [Python script libraries](https://github.com/ankitrohatgi/WebPlotDigitizer).

Extracted data should be stored in a db or .csv file for further analysis.
Also it is possible to represent the digitized plot via [Plotly APIs](https://github.com/plotly/python-api). An auto generating link to Plotly could be great (something like *Graph in Plotly* in [this picture](https://github.com/openworm/muscle_model/issues/30#issuecomment-72689142) )

**Comment by miladjafary** [comment]
@VahidGh Interesting.
I am going to work on it.

**Comment by joebowen** [comment]
It looks like [WebPlotDigitizer](https://github.com/ankitrohatgi/WebPlotDigitizer) is run through client side javascript when it seems like we're more looking for something back-end so we can script with it and then use the plot for other back end functions.

**Comment by VahidGh** [comment]
In the first step of the pipeline, we need to get digitized patch-clamp data, if user already has the data, he/she just needs to upload the file, if not, he/she can digitize it via this digitizer, and the final .csv file generated by the digitizer, could be sent to the back end (in the same way as the first method), for further analysis.

**Comment by joebowen** [comment]
Ok, I'll work on the upload section for the csv file tonight.  On the
backend, do we have the series of steps/scripts to run?

**Comment by VahidGh** [comment]
Great, in addition to .csv file(s), we need to get these parameters of
the patch-clamp study: duration, delay, voltage steps and their
corresponding units (e.g. from -80 mv to 50 mv, in 10 mv increments,
running in 1000 ms)
As for the back-end, not yet, but I hope to get the fitting script finished
in a week or two.
