### ISSUE TITLE
Make ChannelWorm Gitter channel

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#2]
Hi Vahid! :)

Just putting an issue here in case we want to make a channel soon. I don't think I can do it since it is your own repo.

Looking forward to working with you on this!

**Comment by VahidGh** [comment]
Hi Travis, and thank you again :)
I created a temporary room, but it would be better if we create the main one when this repo became a sub-project of the OpenWorm project (as I finish my sum-up documentation, maybe! )
