### ISSUE TITLE
Decide on front end/user interface

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#24]
Some brainstorming questions I have are:
1. What will the page look like?
2. How will the data be displayed?
3. Will the user be able to interact with the data? How so?

Let me know what you guys are thinking about each of these, and if there are any other questions you have about the front-end.

**Comment by VahidGh** [comment]
Milad and I decided on Django+Bootstrap, with some widgets that user can digitize figures and provide additional data for the fitting process.

**Comment by joebowen** [comment]
We've got most of that here: https://github.com/joebowen/ChannelWormDjango

I think it's just missing Bootstrap.

**Comment by VahidGh** [comment]
@joebowen, yes, sorry. Actually the decision on choosing the django+Openshift was made before this by you and me :)
Also we had some changes to the basic structure, to include some Ui features along with other back-end processes like fitting, validation, etc. Thank you for this repo and the syncing script.
Still we have lots of works to do for this app, and any kind of help would be appreciated.

**Comment by joebowen** [comment]
@VahidGh, I'd love to help, just let me know what needs to be done before other people can start contributing.  I'm assuming that we should move the repo over the OpenWorm project.  I'll just have to modify the OpenShift setup to work with the different repo.
