### ISSUE TITLE
Mirror OpenShift git repo on Github

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#26]
Mentioned [here](https://github.com/VahidGh/ChannelWorm/issues/16) but deserves its own issue.

The idea is to link the two repos together so that changes in one are reflected in the other.

**Comment by joebowen** [comment]
I found this and thought it might help.

http://www.redmine.org/projects/redmine/wiki/HowTo_keep_in_sync_your_git_repository_for_redmine

**Comment by joebowen** [comment]
I've started the process [here](https://github.com/joebowen/ChannelWormDjango).  It doesn't fully work, but it's a start.  It might help if I can find the cron logs on the server.

**Comment by joebowen** [comment]
The OpenShift server now updates from [here](https://github.com/joebowen/ChannelWormDjango) every minute through a cronjob.

**Comment by joebowen** [comment]
(OpenShift server url) [http://channelwormdjango-channelworm.rhcloud.com/]
