### ISSUE TITLE
Make digitized and simulated I/V data comparable

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#28]
### Problem

In order to be able to write [validation tests](#27) that use patch clamp data, we need to be able to compare our **simulated** data with the **observed** data. I have a short description of the two data types below.

#### Simulated
We can use [jNeuroML](https://github.com/NeuroML/jNeuroML) to generate `.dat` files from our own LEMS simulation files (`.xml`).
* [Example (this python script creates the `.dat` files)](https://github.com/openworm/BlueBrainProjectShowcase/blob/master/Channelpedia/NML2ChannelAnalyse.py)
* [Example (this shell script generates the `.dat` files using the above script, then makes plots from them)](https://github.com/openworm/muscle_model/blob/master/NeuroML2/analyse_k_fast.sh)

#### Observed
We get back `.csv` files after running plots from the literature through [WebPlotDigitizer](http://arohatgi.info/WebPlotDigitizer/).
* [Example (click "data")](https://plot.ly/~VahidGh/56)

**Comment by pgleeson** [comment]
FYI I've been moving the functionality above to [pyNeuroML](https://github.com/NeuroML/pyNeuroML). See the examples in: https://github.com/NeuroML/pyNeuroML/tree/master/examples

These files are more stable than those in https://github.com/openworm/BlueBrainProjectShowcase, and hopefully pyNeuroML is easier to install...

**Comment by VahidGh** [comment]
@pgleeson, That's great, thanks.
It seems [generating I/F curves](https://github.com/NeuroML/pyNeuroML/blob/master/examples/generate_if_curve.py) is now supported by pyNeuroML, but for generating for example an I/V curve using pyNeuroML+jNeuroML, I guess we should follow something like [this example](https://github.com/NeuroML/pyNeuroML/blob/master/examples/run_jneuroml_plot_matplotlib.py), right?

**Comment by pgleeson** [comment]
@VahidGh, the functionality for generating the current (and activation variable) traces for ion channel can be accessed from command line after installing pyneuroml using: pynml-channelanalysis.

This will generate a LEMS file as before and the output of that can be plotted, or post processed to produce a plot of (max) current through the synapse vs applied membrane potential.

It might be good to update these scripts in muscle_model to use pyneuroml to generate the LEMS, reload the sim, analyse the data, etc. Won't be able to help with this until after the OSB workshop next week, but will try to have a look at it then.

**Comment by VahidGh** [comment]
@pgleeson, please take a look at [this commit](https://github.com/openworm/muscle_model/commit/645991d830654a226975b02590533f59f31e339f). 
I also updated Readme and Travis CI files.
One thing was running plots using pynml, it seems working much slower than jnml!

**Comment by VahidGh** [comment]
@pgleeson, there was some building errors from Travis CI when running pynml-channelanalysis.
[This issue](https://github.com/NeuroML/pyNeuroML/issues/3), might help solving these errors.

**Comment by VahidGh** [comment]
@pgleeson, thank you for [these](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302/tune) helpful scripts :)

**Comment by travs** [comment]
We have [one test](https://github.com/VahidGh/ChannelWorm/blob/b8e3b3c8a684b27565b41403e071e6a7e2d9a553/tests/IVCurve_Model.ipynb) that compares simulated and observed I/V data, so this issue can be closed.
