### ISSUE TITLE
Decide what Capabilities our Model(s) will have

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#29]
### Background

SciUnit uses Capabilities to interface between Models and Tests. 

In [this example](https://github.com/scidash/sciunit/blob/master/sciunit/capabilities.py), the Capability [`ProducesNumber`](https://github.com/scidash/sciunit/blob/master/sciunit/capabilities.py#L7-L11) describes the method(s) that Models like [`UniqueRandomNumberModel`](https://github.com/scidash/sciunit/blob/master/sciunit/capabilities.py#L13-L18) must implement in order to "have" the Capability.

Models that have all the Capabilities listed [in a Test's `required_capabilities`](https://github.com/scidash/sciunit/blob/master/sciunit/tests/example.py#L9) can be run in that Test. This ensures that, when running a Suite, Tests only run on Models that make sense (i.e. that are relevant to the test).

### Code

Now the question seems to be: which methods do we need Models to implement in order to be relevant to a given Test.

This code will mostly be method headers, followed by docstrings that describe what the method should do when implemented. There is a lack of method bodies because implementing a given method is left up to the Model that has the Capability.

This will be developed in tandem with writing Tests, which is tracked in a separate issue (#32).

@gsarma

**Comment by travs** [comment]
As a start, the first Capability can be `Generates_IV_curve`. This can be taken to mean the Model will actually produce a set of data that can be plotted as a current-voltage relationship when run with [iv_analyse.py](https://github.com/openworm/BlueBrainProjectShowcase/blob/master/Channelpedia/iv_analyse.py).

@rgerkin 
Do you think this is this a sensible Capability? And how could we turn this into code so that it would be easily implemented by a Model?

@gsarma

**Comment by rgerkin** [comment]
So `Generates_IV_Curve` would probably inherit a few other things like `Receives_Current` and `Produces_Membrane_Potential`, since those would be required for an IV curve to make any sense.  

Then the `Generates_IV_Curve` methods would probably just be the one method `generate_iv_curve`, although maybe there are others, and the arguments to it would be a list or array of currents, and step durations, or maybe a list of waveforms if we are going to be using some standard representations for what a current injection should look like, using NEO or something (see #40).  Then `generates_iv_curve` would call whatever methods found in `Receives_Current` and `Produces_Membrane_Potential`, etc. would be required to get the data points for the IV curve.

**Comment by slarson** [comment]
@travs I think we need to start by stubbing out `Receives_Current` and `Produces_Membrane_Potential` with the arguments @rgerkin suggests, without implementation, and then fit the process of generating IV curves that exists in @rayner 's work into those as a second step.  I'll comment further on #40 but it looks like using [neo.analogsignal](https://pythonhosted.org/neo/core.html#data-objects) may be the right structure he's looking for.  

@travs maybe can you generate another issue that just focuses on this?

**Comment by rgerkin** [comment]
You can look at [NeuronUnit capabilities](https://github.com/rgerkin/neuronunit/blob/master/capabilities/__init__.py) for a start, and try to match it when you can, but I'm not sure yet if the totality of ChannelWorm-related capabilities will be much larger than what I intend to have in NeuronUnit or not.  If it isn't, you can just add them in NeuronUnit and import, but if it is you'll have your own capabilities.py here.  In either case, I can always edit later to import from NeuronUnit the ones that they have in common.
