### ISSUE TITLE
Install PyOpenWorm as a library rather than include it as a submodule

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#35]
This can be done with 
```bash
pip install git+https://github.com/openworm/PyOpenWorm.git@channelworm
```

**Comment by miladjafary** [comment]
Great. 
SO PyOpenWorm install as lib and we use it in project as a third party lib? 
You'r implementation for channel worm is included in PyOpenWorm which is install as a lib ?

**Comment by travs** [comment]
@miladjafary

Yes, the data management/modelling will be done using PyOpenWorm as an external library. 

The version of PyOpenWorm we will use is on the "channelworm" branch right now, but this may change to the master branch depending on what happens in PyOpenWorm.

**Comment by travs** [comment]
This is happening now.

**Comment by VahidGh** [comment]
@travs, great. Do we still need [this](https://github.com/VahidGh/ChannelWorm/blob/master/.gitmodules) sub-module?

**Comment by travs** [comment]
@VahidGh  Nope! I'll get rid of it
