### ISSUE TITLE
Deploy current version of the Django+Bootstrap app

### ISSUE THREAD

**Issue by slarson** [VahidGh/ChannelWorm#38]
According to @miladjafary : "it's sunds that @joebowen found a way that we can put code in Repo and deployed automatic in OpenShift"

**Comment by joebowen** [comment]
This is true.  I can finish configuring the github.com project when I have
more details.

**Comment by travs** [comment]
@miladjafary 
I can see the code to the web app now. Is there a place where this is online already, or are we still waiting to deploy?

**Comment by miladjafary** [comment]
@travs no there is not online demo yet.
you can deploy it localy. We should find a server  for online demo.

**Comment by slarson** [comment]
Looks like we've [done this](http://channelwormdjango-channelworm.rhcloud.com/).  Is it ok for it to stay here for now?

**Comment by miladjafary** [comment]
@slarson I think for now is enough 
we can use it if for online demo also we can use it for data gathering
