### ISSUE TITLE
Implement prototypical acceptable range calucations in SciUnit Tests

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#48]
There are not yet any Tests to perform acceptable range calculations on, but the need will surely arise with the use of any kind of complex statistical test.

This is distinct from #36 in that the results are not binary passes/fails, but a warning system to tell us when a Model's results are suspicious and should be investigated.

cc: @rgerkin @slarson @gsarma

**Comment by rgerkin** [comment]
@travs Let's say it's a sciunit.ZScore, maybe you `assert abs(score.score)<5` or something that alerts you if it's too far away from the expected value (i.e. from the data), but the overall judgement of the quality of the model is going to have a different decision function in terms of how it views that score.  

But I think for now you should just `assert score.__class__ is not sciunit.ErrorScore` or whatever would ensure that tests are running successfully.  Use of sciunit.ErrorScore has traditionally been for catching actual Exceptions, which means you could actually raise a CrazyScoreException or something else you make up for those scores which indicate that something is wrong.

**Comment by rgerkin** [comment]
@travs Just eye-balling it, I set 100 pA^2 to be the minimum acceptable sum-squared difference between the model and experiment IV curves.

**Comment by travs** [comment]
Excellent, we can decide on what the value should be for this acceptable range at a later date.

Since we have a prototype for this now, I will close the issue.

Thanks again @rgerkin !
