### ISSUE TITLE
Include branch of PyOpenWorm as submodule

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#5]
The idea here is to create a branch of PyOpenWorm that has a data model for `ion channel` and other data that would be convenient for ChannelWorm's purposes (ex: `SI unit`). 

The changes made to the PyOpenWorm `ChannelWorm` branch should be forward-compatible with PyOpenWorm. In other words, they should be merged into the `master` branch of PyOpenWorm further down the road, and any additions should keep this prospect in mind.

**Comment by VahidGh** [comment]
Good idea @travs :+1:
