### ISSUE TITLE
Create stub for I/V Curve-producing model

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#50]
We can begin creating a skeleton for an ion channel Model that will be used in SciUnit tests.

This will implement the Capabilities we have already enumerated (#41)

Needed for #27 to move forward (imports)

**Comment by VahidGh** [comment]
In [my implementations](https://github.com/VahidGh/ChannelWorm/blob/cwFitter/cwFitter/Evaluator.py#L63), I've considered the cost function for evaluating I/V cures, as sum of the squared distances between the sample and simulated points divided by the number of points and trying to minimize this.
I was thinking about storing a normalized version of this measurement and comparing with other models.
How is this different from the approach is going to be taken by the SciUnit?
