### ISSUE TITLE
Digitization module is broken after upload in openshift

### ISSUE THREAD

**Issue by miladjafary** [VahidGh/ChannelWorm#64]
Digitization module in [here](http://channelwormdjango-channelworm.rhcloud.com/digitizer/5) is broken after upload in openshift. Because the required js and css of Digitization module couldn't be find.

**Comment by slarson** [comment]
cc: @joebowen

**Comment by VahidGh** [comment]
Also we have too many directories named channelworm which causing difficulties in module namings and calls.
@joebowen, Is there a way to make some changes to the OpenShift configuration file to work based-on our desired structure?

**Comment by VahidGh** [comment]
@joebowen, It seems like there is a [new update](https://blog.openshift.com/openshift-online-march-2014-release-blog/) to the OpenShift that allows using a simpler template directory.
I reverted the master branch to the latest stable version. Would you please add the new configuration files based on this link?

**Comment by joebowen** [comment]
@VahidGh, So I'm not sure what to do here.  We were using that new updated structure for our directory structure.

**Comment by joebowen** [comment]
This is done.
