### ISSUE TITLE
Changing web app package name 

### ISSUE THREAD

**Issue by miladjafary** [VahidGh/ChannelWorm#65]
Changing web app package name as a standard for define python module

**Comment by VahidGh** [comment]
@miladjafary, Following discussions in #64, I think now this could be a better naming approach for the package:
channelworm (django root directory, all lower case) -> channelwormapp (or channelworm_app).
In this way we can call modules simpler, eg. channelworm.digitizer, etc.

**Comment by miladjafary** [comment]
@VahidGh  Aggred .Also we can miss channelworm form second package and remain app ,so in this way we have 
channelworm ( django root dir)
------\ app
------\digitizer
------\ion_channel
 . . . 
so we can call modules simpler than before . e.g : channelworm.app, channelworm.digitzie

**Comment by VahidGh** [comment]
Yeah, or even *webapp* would be more meaningful.

**Comment by VahidGh** [comment]
@miladjafary, would you please apply these changes ASAP, to fix the final structure and then go farther based on these naming?

**Comment by miladjafary** [comment]
@VahidGh done. Now you can do your changes.
note : 
1. Package name should be lower case.
2. Package name with 2 word or more should be separated by underline (_).
 So you should change cwFitter to cw_fitter. Also I sujest you remove "cw". In this case module can adders as 
**channelworm.fitter** instead of **channelworm.cw_fitter**
