### ISSUE TITLE
Get webapp back online

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#66]
Not sure what's happening, but the [link I've been using](http://channelwormdjango-channelworm.rhcloud.com/) is giving me an error now.

Related to [this](https://github.com/VahidGh/ChannelWorm/issues/64).

**Comment by slarson** [comment]
cc: @joebowen

**Comment by joebowen** [comment]
Looks like there's an internal server error.  I'll check out the logs when
I get home from work tonight.

Joe

**Comment by joebowen** [comment]
Web app is back online now

**Comment by travs** [comment]
Thanks @joebowen !
