### ISSUE TITLE
Add ion channel object and related data to the PyOpenWorm

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#7]
@travs, Here is my proposed scheme:
* Every cell has 0-n ion channel with these properties:
  * membrane capacitance
  * cell surface area
  * internal ion concentration
* Every ion channel has 0-n model with these properties:
  * references
  * contributors identity
  * experiment's condition properties, like temperature, age of the organism, etc
  * channel properties: rev potential, ion type, ligand ion types, activation/inactivation type and related parameters 
* Every ion channel has also genetic, etc properties independent of the model. required ones, could be inserted into the PyOW from [this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdEd6S0dfVnE4blhaY2ZIWDBvZFNjT0E#gid=1) and others, could be represented by calling WormBase APIs!
* Also these data could be included:
  * ion channel's known mutants (that could be a child of the main ion channel table)
  * ion channel-related diseases (channelopathies) with refs
* Cell-channel relation
  * channel density specific to the cell type
  * specific capacitance 
* There is a synapse between two cells that has properties like ion concentration, ion decay time, etc. [This](http://www.neuroml.org/NeuroML2CoreTypes/Synapses.html) could be helpful (for the simulation purposes)
* SI units, that could be retrieved from [here](http://www.neuroml.org/NeuroML2CoreTypes/NeuroMLCoreDimensions.html).

We can start with properties in [this script](https://github.com/openworm/muscle_model/blob/master/BoyleCohen2008/PythonSupport/Main_Version/compareToNeuroML2.py) for the prototype schema and then improve it using NeuroML components (e.g. [cells](http://www.neuroml.org/NeuroML2CoreTypes/Cells.html), [channels](http://www.neuroml.org/NeuroML2CoreTypes/Channels.html), etc)

As for the channel naming, I suggest using subfamilies (e.g. [Kv1, etc](http://www.wormbook.org/chapters/www_function/function.html)).

Also, for most of these properties we need to include references, from which data extracted, that I guess we can handle it via RDF supported in the PyOW, but I'm not sure what's the best way to implement it.

In addition, we need another DB for specific data in this project (which I'll cover it via another issue)

**Comment by travs** [comment]
Excellent stuff Vahid!

PyOW has support for attaching `Evidence` objects to db objects in RDF so we can incorporate that for references and contributor indentities. 

All of the other data you mentioned makes sense to me, and we can wrap WormBase API calls within PyOpenWorm to get up-to-date information from WormBase, as you say 

When you say:
> Every cell has 0-n ion channel with these properties:
- membrane capacitance
- cell surface area
- internal ion concentration

These seem like *cell* properties, so these should be properties of the `cell` object, no?
Also, these things would be in a dynamic state, if I am not mistaken, so would it be appropriate to store them in a db?

Minus clarification on the above points, I agree with your scheme. We can have a more fine-grained discussion gitter chat, or here, whichever you prefer.

**Comment by VahidGh** [comment]
@travs, Great! 
As for the cell properties issue, we need these properties for modeling purposes, but they are not specific to the channel and could be different from cell to cell.
For example, we may have egl-19 in both muscle cell and motor neurons, but these properties could be different for these cell types.
Actually, I was thinking about two different approaches of the modeling, one based on the patch clamp data (in which we could have the whole object as a model), but for the modeling approach based on homology modeling, and protein structure, there are different entities from different models (experiments) that yield the final model, so we could have separate objects, from different references, and putting them together, facilitates the final modeling and optimization process.
Although for the later approach, I'm going to design another DB, as my researches completed.
And regarding to the dynamic properties, we just need to store the initial states.

**Comment by travs** [comment]
Ok, that makes sense. 
I have a quick scheme drawn up here, with some of the main points we've been discussing. It's rough, but if you agree on the structure I can get started modelling it in PyOpenWorm.

Eventually, the goal will be to get each `ChannelModel` as a NeuroML2 object.
![](https://cloud.githubusercontent.com/assets/7369273/6252388/89d39ab4-b774-11e4-8fda-bf63f6d7ef93.jpg)

**Comment by VahidGh** [comment]
That's cool. Also we need to add channel kinetic properties (activation/inactivation parameters, etc) in order to generate a NeuroML2 object as you said.
Additionally, we can convert the spreadsheet to sql, and keep it as genetic properties of ion channels. we have lots of useful data in this file that could be used in our scripts and for representation purposes.

**Comment by slarson** [comment]
A start on this is now {here](https://github.com/openworm/PyOpenWorm/blob/alpha0.5/PyOpenWorm/channel.py#L157-L183) -- let's raise new issues to augment this
