### ISSUE TITLE
Storage method of biological information for ion channels

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#9]
The initial source of data for biological properties of ion channels is [this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdEd6S0dfVnE4blhaY2ZIWDBvZFNjT0E&usp=drive_web#gid=) which is obtained from WormBase.
In order to better structure and represent these biological data via ChannelWorm, we need to store (at least important ones) in a DB (preferably PyOW). but there is the problem of updating and synchronization with WormBase.
Two options are:
* Storing all the data in a DB and developing a scheduler to keep data up-to-date
* Just store important IDs and links and represent data by calling [WormBase APIs](http://www.wormbase.org/about/userguide/for_developers/api-rest#10--10)

**Comment by travs** [comment]
We've decided that we will use the web app's db as an intermediary between the data source (papers) and PyOpenWorm.

Synchronization and other questions can get their own individual issues as they become more apparent.
