### ISSUE TITLE
muscle_model missing documentation

### ISSUE THREAD

**Issue by cheelee** [VahidGh/ChannelWorm#93]

**Comment by cheelee** [comment]
In the muscle_model repository, NeuroML2 folder. The README.md instructions ask the user to try:
    jnml LEMS_Figure2A.xml

but does not explain how one should get hold of jnml. For me, I found it in the jNeuroML repository, cloned it, and followed the README.md instructions there. That appeared to be successful, and I was subsequently able to run from the jNeuroML folder:

./jnml <pathto>/muscle_model/NeuroML2/LEMS_Figure2A.xml

**Comment by travs** [comment]
@cheelee Thank you for the report; we certainly need to document this.

 I've moved this issue over to the openworm/muscle_model#45
