### ISSUE TITLE
WSGI application 'web_app.wsgi.application' could not be loaded

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#94]
New configurations for deploying web app on the OpenShift, causing this error when trying to run it locally:
`WSGI application 'web_app.wsgi.application' could not be loaded`

Commenting out [this line](https://github.com/VahidGh/ChannelWorm/blob/master/channelworm/web_app/settings.py#L74) solves the problem, but may cause some other problems in the OpenShift side.

**Comment by VahidGh** [comment]
@joebowen, would you please take a look at this issue.

**Comment by miladjafary** [comment]
@VahidGh I think it's not related to openshift changes. 
it's about APP. I will check it asap.

**Comment by joebowen** [comment]
This should be fixed now.

**Comment by cheelee** [comment]
So should wsgi/wsgi.py be removed from the repository in that case?
