### ISSUE TITLE
Make fields in models.py nullable

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#95]
@joebowen said:
> So the issue is that the fields in ion_channel/models.py are "non-nullable fields" but don't have defaults. So when you do a makemigrations, it prompts the cron script (which is the true problem, cause cron scripts aren't "promptable") to provide a one-off default. The real fix would be to give the fields defaults or make them nullable

**Comment by joebowen** [comment]
[Example](https://github.com/VahidGh/ChannelWorm/blob/4e67e63a3ae95d3971e94fc19e681b1fb4c49433/channelworm/ion_channel/models.py#L31)

**Comment by travs** [comment]
@joebowen 
Is this issue resolved now?

**Comment by joebowen** [comment]
@travs my understanding was that the bigger fix for this was to create a
sync job but I'm not sure where that stands.  @vahidgh might better be able
to answer this.

**Comment by VahidGh** [comment]
@travs, @joebowen, yes, with new models and updates this is now resolved.
