### ISSUE TITLE
Merge cwFitter branch

### ISSUE THREAD

**Issue by rgerkin** [VahidGh/ChannelWorm#99]
I'd like the SciUnit stuff to work without needing multiple branches of ChannelWorm checked out.  Can we merge the cwFitter branch back in, or at least patch master will all of its current content?

**Comment by rgerkin** [comment]
@VahidGh @travs

**Comment by VahidGh** [comment]
@rgerkin, we had some name changing issue. Now the master branch is stable and you can call it via `channelworm.fitter`. It's still under development but in the next step we will integrate this with the data model and you can have access to data much easier.
